#!/usr/bin/env python3
"""Drives an interactive harness session through a pty to check the wake path.

Headless doesn't work here: cursor-agent -p runs no hooks at all
(docs/verification/2026-08-31-plugin-wake.md). And typing text plus Enter
must be SEPARATE -- sending them together makes Cursor receive the text but
not submit it.

WARNING ABOUT LOCAL ECHO: the pty echoes back exactly what we write into it,
so `--expect` would also match the `--send` text itself. Measured: running
the driver against `sleep 30` -- a program that never reads stdin at all --
with `--send hello --expect hello` still PASSES. So `--expect` MUST be a
string GENERATED BY the agent, not the string we sent it. For the Cursor
smoke test, that's `vizier:` inside the hook's follow-up.

Total run time is --wait PLUS roughly 10-11 seconds: 8s waiting for the TUI
to come up, 2s pumping after sending, and up to ~1.2s shutting down when the
child resists signals (0.2s Ctrl-C + 0.5s waiting for SIGTERM + 0.5s waiting
for SIGKILL). Every normal step has an upper bound.

Usage: pty-drive.py <cmd> [args...] --send <text> --expect <marker> --wait <sec>
"""
import os, pty, re, select, signal, struct, sys, termios, fcntl, time

ANSI = re.compile(rb'\x1b\[[0-9;?]*[a-zA-Z]|\x1b\][^\x07]*\x07|\x1b[()][B0]|\x1b[=>]')

def main():
    argv = sys.argv[1:]
    send = expect = None
    wait = 120
    cmd = []
    i = 0
    while i < len(argv):
        if argv[i] == "--send": send = argv[i+1]; i += 2
        elif argv[i] == "--expect": expect = argv[i+1]; i += 2
        elif argv[i] == "--wait": wait = int(argv[i+1]); i += 2
        else: cmd.append(argv[i]); i += 1
    if not cmd or send is None or expect is None:
        print(__doc__); return 2

    pid, fd = pty.fork()
    if pid == 0:
        os.environ.update(TERM="xterm-256color", LINES="40", COLUMNS="120")
        os.execvp(cmd[0], cmd)
    fcntl.ioctl(fd, termios.TIOCSWINSZ, struct.pack("HHHH", 40, 120, 0, 0))

    # SIGTERM must become an exception, otherwise `finally` does NOT run.
    # Measured: pressing Ctrl-C (SIGINT) cleans up the child properly, but
    # `kill` (SIGTERM) kills Python immediately and the child agent SURVIVES
    # -- exactly the path a wrapper with a timeout would use. Registered
    # after the fork so it only applies to the parent process; the child has
    # already execvp'd and had its handler reset to the default.
    def _on_term(_signum, _frame):
        raise KeyboardInterrupt
    signal.signal(signal.SIGTERM, _on_term)

    buf = b""
    def pump(sec):
        nonlocal buf
        end = time.time() + sec
        while time.time() < end:
            r, _, _ = select.select([fd], [], [], 0.3)
            if not r: continue
            try: d = os.read(fd, 65536)
            except OSError: return False
            if not d: return False
            buf += d
            if expect.encode() in ANSI.sub(b'', buf):
                return "found"
        return True

    def shutdown():
        # Ctrl-C through the pty first (the polite way to ask a TUI), then
        # escalate through signals and REAP. Without the reap + SIGKILL step,
        # an agent that installs its own TERM/INT/HUP handler would survive
        # and become an orphan -- reproduced, and exactly the kind of process
        # leak this project already fixed once in the wake library. A driver
        # that leaves a live cursor-agent behind on every call is not
        # something that can be handed to the captain.
        try:
            os.write(fd, b"\x03"); time.sleep(0.2); os.write(fd, b"\x03")
        except OSError:
            pass
        for sig, grace in ((signal.SIGTERM, 0.5), (signal.SIGKILL, 0.5)):
            try:
                os.kill(pid, sig)
            except ProcessLookupError:
                break
            deadline = time.time() + grace
            while time.time() < deadline:
                try:
                    done, _ = os.waitpid(pid, os.WNOHANG)
                except ChildProcessError:
                    return
                if done == pid:
                    return
                time.sleep(0.05)
        try:
            os.waitpid(pid, 0)
        except (ChildProcessError, OSError):
            pass

    # try/finally, NOT just try/except OSError. Catching only OSError still
    # leaves every other exception unhandled -- and the most likely one is
    # KeyboardInterrupt: the captain pressing Ctrl-C on the very smoke run
    # in progress. In that case `shutdown()` wouldn't run and the agent would
    # leak, exactly the hole just closed above. `finally` covers every exit path.
    found = None
    write_err = None
    try:
        pump(8)                                  # let the TUI finish coming up
        # The write can raise OSError if the child has already died (Errno 5 on a pty).
        os.write(fd, send.encode()); pump(2)     # type the text
        os.write(fd, b"\r")                      # Enter, SEPARATELY
        found = pump(wait)
    except OSError as e:
        write_err = e
    finally:
        shutdown()
        try:
            os.close(fd)
        except OSError:
            pass

    if write_err is not None:
        print(f"FAIL: could not write to the pty ({write_err})", file=sys.stderr)
        return 1

    if found == "found":
        print(f"PASS: saw {expect!r}"); return 0
    print(f"FAIL: did not see {expect!r} within {wait}s", file=sys.stderr)
    sys.stderr.write(ANSI.sub(b'', buf)[-2000:].decode('utf-8', 'replace'))
    return 1

if __name__ == "__main__":
    raise SystemExit(main())
